### ISSUE TITLE
링크 페이지 마크다운 생성 👉 `links.md`

### ISSUE THREAD

**Issue by justinyoo** [matdaaiga-kr/matdaaiga-kr.github.io#17]
- `/src/MatdaAIga.Generator/input/pages` 디렉토리에 `links.md` 문서 생성하기
- 마크다운 문서 안의 frontmatter 형식은 같은 디렉토리의 `about.md` 문서 참조할 것

**Comment by krsy0411** [comment]
<img width="277" alt="Image" src="https://github.com/user-attachments/assets/ae0d1bae-f753-479f-802c-8acc333bc815" />

포맷은 맞추되 문구는 제가 임의로 넣어두면 되는 게 맞을까요?
@justinyoo

**Comment by krsy0411** [comment]
<img width="648" alt="Image" src="https://github.com/user-attachments/assets/f2368120-28da-4dd8-82dd-947dbb85666c" />

금재 PR보고 간단하게 예시용으로 작성해봤습니다. 요런 형태의 예시로 스타일링 작업을 해나면 될까요? 아이콘은 사이즈를 좀 줄이고 instagram 아이콘, X 아이콘, 링크드인 아이콘이 나열되어있다고 생각해주시면 될거 같습니다.

👇👇👇 로컬 환경에서 렌더링시켰을 때 입니다(스타일링 적용 전)
<img width="973" alt="Image" src="https://github.com/user-attachments/assets/f5297a20-9188-46c2-8c90-298eea3c2919" />

**Comment by justinyoo** [comment]
기본적으로 YAML 파일 구조가

```yaml
- title: hello world
  url: https://hello-world.com
  image_url: /images/hello-world.png 또는 https://hello-world.com/images/hello-world.png
- title: lorem ipsum
  url: https://lorem-ipsum.com
```

이런 식이 될텐데, `image_url` 속성은 필수는 아니라서 위와 같은 경우라면 마크다운은 아래와 같은 식으로 만들어질 겁니다

```markdown
- [![hello world](/images/hello-world)](https://hello-world.com)<br>
  [hello world](https://hello-world.com)
- [lorem ipsum](https://lorem-ipsum.com)
```
