### ISSUE TITLE
YAML 스키마 정의

### ISSUE THREAD

**Issue by justinyoo** [matdaaiga-kr/matdaaiga-kr.github.io#19]
YAML 문서 형식 예:

```yaml
- title: hello world
  url: https://matdaaiga.kr/hello-world
- title: lorem ipsum
  url: https://matdaaiga.kr/lorem-ipsum
  image_url: /images/lorem-ipsum.png
- title: github
  icon: github
  url: https://github.com/matdaaiga-kr
- title: instagram
  icon: instagram
  url: https://instagram.com/matdaaiga
```

- required:
  - `title`: string type
  - `url`: string type - must start with `https://`
- optional:
  - `image_url`: string type - must start with `/images/`
  - `icon`: enum type - `github`, `instagram`, `linkedin`, `youtube`, `x`, `bluesky`, `threads`, `website`

**Comment by YoonKeumJae** [comment]
기본적인 구조는 아래와 같습니다. 

```yaml
- title: ""
  url: ""
  img: ""
```

`title`: required, string type
`url`: required, string type, must start with `https://`
`img`: optional, string type, must start with `/images/`

icon을 일일이 입력하는 것 보다, 주어진 url에서 favicon을 추출해 표시하는 것이 가장 효율적일 것이라 생각해 생략했습니다. 
아래는 예시 코드입니다. 

```yaml
- title: "깃허브"
  url: "https://github.com/"
- title: "링크드인"
  url: "https://www.linkedin.com/"
  img: "/images/linkedin.png"
```
